#import "../lib.typ": *
= Future work<sec:future_work>
The focus of this thesis is the $k$-means clustering objective, which is one of the most well known and studied clustering objectives. However, many other widely used clustering objectives exist. Two alternative centroid-based clustering objectives outside $k$-means are $k$-medoids @leonardPartitioningMedoidsProgram1990 and $k$-medians. $k$-medoids defines a cluster center to be the median member point in that cluster, and $k$-medians defines the cluster representative to be the median of all points in the cluster, which is not necessarily a point from the input data. Future work could include an analysis of how the novel methods introduced in this thesis handle these alternative clustering objectives.

The TGCF method introduced in @sec:tgcf is unable to generate counterfactuals for some instances in higher dimensions. The fidelity was enhanced by introducing a leaf-splitting step, which guarantees that at least some leaves result in valid counterfactuals. The intuition behind this approach was that some leaves had the potential to result in invalid counterfactuals, and hence validity could be improved by cutting off the invalid parts. This increases validity in higher dimensions, but it does not always guarantee a valid counterfactual for all instances, as shown by the low _%Explained_ score on the Breast Cancer dataset. Another approach would be to develop an alternative algorithm for creating the tree, instead of relying on existing methods. With this, one might be able to create a tree better suited for the purpose of generating counterfactuals by incentivizing smaller trees and preventing it from splitting on every feature in order to increase accuracy. For example, an algorithm may use an objective based on eliminating empty space, much like the fidelity improvement step. This might also solve the problem of the generated counterfactuals having a low sparsity, which we noted for TGCF.

In @sec:experiments we compared the novel methods with two BayCon variations adapted to the clustering task as presented in @spagnolCounterfactualExplanationsClustering2024. However, there exists an additional state of the art counterfactual algorithm for clustering called CFClust @vardakasCounterfactualExplanationsKmeans2025, which we described in @sec:cfclust. At the time of writing this thesis, the CFClust implementation was not yet available to the public, which means we were not able to include it in the experiments. Given that CFClust is also a method in the very limited field of counterfactual generation for clustering, it would be ideal to include it in a comparison between existing methods and the novel algorithms introduced in this thesis.

In @sec:invalidation we discussed whether the results concerning _invalidation_ and _correction_ are significant enough to warrant further analysis. We argued that the results could be excluded in our analysis, since so few cases of either invalidation or corrections were observed. However, in certain applications, an invalidation rate of 6\/1000 may be an issue worth considering. Future work could include researching this phenomenon further, and perhaps developing algorithms which guarantee that invalidation is impossible. Similarly, one might be able exploit the properties of correction to yield counterfactuals with better similarity to the original instance $x$, by generating an initially invalid counterfactual which gets corrected when applied to the data.

In @Necs we argued informally that the NeCS optimization problem is computationally hard. A more in-depth analysis could include a formal proof. Additionally, we proved the 3 lemmas required for yielding an approximation guarantee for the greedy algorithm using a static set of safe features $F^"safe"$. Proving an approximation guarantee for the complete set of features $F$ would result in an improved algorithm with even better guarantees.